config/routes.rb
Rails.application.routes.draw do
  root 'article#index'
  resources :article do
    resources :comment
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comment
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter , presence: true ,length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  def index
    @article=Article.all
  end
  def new
    
  end
  def show
    @article=Article.find(params[:id])
  end
  def edit
    @article=Article.find(params[:id])
  end

  def create
    @article = Article.create(article_params)
    @article.save

    # dòng này
    # redirect_to @article
    # với dòng này
    redirect_to article_index_path
  end
  def update
    @article=Article.update(article_params)
    redirect_to article_index_path
  end
  def destroy
   @article = Article.find(params[:id])
   @article.destroy
    redirect_to article_index_path
  end

  private 
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
    def show
        @comment=Comment.find(params[:id])
    end
    def create
        @article=Article.find(params[:article_id])
        # @comment=Comment.new(comment_params)
        # @article.comments.create(comment_params)
        if @article.comment.create(comment_params).save
            flash[:notice]=nil;
            redirect_to @article
        else
            flash[:notice]='Please enter your data'
            # redirect_to @article
            render "article/show"
        end
       
        # redirect_to @comment
    end
    
    private
    def comment_params
      params.require(:comment).permit( :commenter, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/article/edit.html.erb
<%= form_with scope: :article, url:article_path,method: 'put', local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, value: @article.title, disabled: true %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/article/index.html.erb
<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th>create at</th>
        <th>Action</th>
  </tr>
        <% @article.each do |item| %>
    <tr>
        <td><%= item.title%></td>
        <td><%= item.text%></td>
        <td><%= item.created_at%></td>
       <td> <%= link_to "delete", article_url(item.id),method: :delete, 
        data: {
            confirm: "delete item ?"
        }
        %>
        <%= link_to "show", article_path(item.id) %>
        <%= link_to "edit", edit_article_path(item.id) %>
        </td>
    </tr>
<% end %>
</table>
<%= link_to "create",new_article_path %>

app/views/article/new.html.erb
<p>this is new page</p>

<%= form_with scope: :article, url:article_index_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/article/show.html.erb
<%= @article.title%>
<br/>
<%= @article.text%>
<br/>
<p id="notice">
<%= flash[:notice] %>
<%@article.comment.each do |item| %>
  <strong>commenter:</strong>
    <%=item.commenter%>
  <br/>
  <strong>Text:</strong>
    <%= item.body %>
<% end %>
<br/>
<div id="div1">this is div 1111111111111111111</div>
<%= render "comment/form"%>
<%= link_to "back", root_path%>
<%= stylesheet_link_tag "testcss.css" %>

app/views/article/test.html.erb
<p> test in article</p>

app/views/comment/_form.html.erb
<%= form_with scope: :comment, url:article_comment_index_url(@article.id), local: true do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
 
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
 
  <p>
    <%= form.submit value:"add a comment" %>
  </p>
<% end %>

app/views/comment/new.html.erb
<p>this is new comment</p>

app/views/comment/show.html.erb
<h1>this is showw in comment</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>